### ISSUE TITLE
Lazy load version detection as it issues HTTP request

### ISSUE THREAD

**Issue by ronoaldo** [filipenos/gaesdk#1]
Instead of loading a remote URL at init(), this should be done after parsing the arguments, as the default version is overwrittern by user using the --version flag.

Also, there can be some problems in doing HTTP requests at init(), as it should in theory, be as low as possible work on that function.

**Comment by filipenos** [comment]
Resolved on https://github.com/filipenos/gaesdk/commit/c980f52a3348d4e643197855b29249373daaaef9
