### ISSUE TITLE
Use ioutil.Tempfile() or similar to perform the temporary download

### ISSUE THREAD

**Issue by ronoaldo** [filipenos/gaesdk#2]
Not only the current implementation poses a small risk to overwrite a user file, it has a temporary directory hardcoded, so that may not be desirable if the user has made a change.

See here: https://golang.org/pkg/io/ioutil/#TempFile

**Comment by filipenos** [comment]
Resolved https://github.com/filipenos/gaesdk/commit/593a1a2ab5088bc1c0ab12de050428bb81015fb1
